#cloud-config
hostname: ${HOSTNAME}
swap:
  filename: /swapfile01
  size: "auto"
  maxsize: 2097152000 # 2GB
packages:
  - docker
  - git
  - vim
  #- zsh
  #- mc
  #- awscli
package_update: true
package_upgrade: true
package_reboot_if_required: true
runcmd:
  - [ git, clone, --branch, test, "https://github.com/diepes/EngAssNginx.git", /opt/gitrepo ]
  - [ /opt/gitrepo/scripts/cloud-config-initial-setup.sh, ]
#groups:
# write_files:

final_message: "The system is finally up, after $UPTIME seconds"
