#cloud-config
hostname: ${HOSTNAME}
swap:
  filename: /swapfile01
  size: "auto"
  maxsize: 2097152000 # 2GB
packages:
  - docker
  #- zsh
  #- mc
  #- awscli
package_update: true
package_upgrade: true
package_reboot_if_required: true
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, --no-block, docker.service ]
  - [ systemctl, enable, docker.nginx.service ]
  - [ systemctl, start, --no-block, docker.nginx.service]
groups:
  - docker: [root,ec2-user]
write_files:
- path: /etc/systemd/system/docker.nginx.service
  permissions: '0644'
  owner: root:root
  content: |
      [Unit]
      Description=Nginx Docker Service
      After=docker.service
      Requires=docker.service
      # After=docker.?.service
      # Requires=docker.?.service
      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker stop nginx
      ExecStartPre=-/usr/bin/docker rm nginx
      ExecStartPre=/usr/bin/docker pull nginx:stable
      ExecStart=/usr/bin/docker run --name nginx --rm -v /content:/usr/share/nginx/html:ro -p 80:80 nginx:stable
      [Install]
      WantedBy=multi-user.target
- path: /content/index.html
  permissions: '644'
  content: | 
      Welcome to Pieter's flash website !   
final_message: "The system is finally up, after $UPTIME seconds"
